# Generated by Django 2.2 on 2019-08-26 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date published')),
                ('password', models.CharField(max_length=200)),
                ('taxi', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='driver.Taxi')),
            ],
        ),
    ]
