# Generated by Django 2.2.3 on 2019-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_students_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='paraents_phn',
            field=models.IntegerField(default=1),
        ),
    ]
