# Generated by Django 2.2.3 on 2019-07-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_students_paraents_phn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='paraents_phn',
            new_name='parrents_phone',
        ),
        migrations.RemoveField(
            model_name='students',
            name='phone',
        ),
    ]
