# Generated by Django 2.2 on 2019-08-22 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190718_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='parrents_phone',
        ),
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Sections'),
        ),
    ]
