# Generated by Django 2.2 on 2019-08-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_driver_parent_taxi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='taxi',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Taxi',
        ),
    ]
